
name: Android Publish

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      dotnet-version-target:
        required: true
        type: string
      project-file:
        required: true
        type: string
      project-folder:
        required: true
        type: string
      build-config:
        required: false
        type: string
        default: 'Release'
      build-version:
        required: true
        type: string
#    secrets:      
#      keystore-password:
#        required: true
#      keystore-alias:
#        required: true
#      keystore:
#        required: true
#      playstore-service-account:
#        required: true


jobs:
  publish-android:
    runs-on: windows-latest
    name: Android Publish

    steps:

      - name: Setup .NET ${{ inputs.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - uses: actions/checkout@v4
        name: Checkout the code

    # This step might be obsolete at some point as .NET MAUI workloads 
    # are starting to come pre-installed on the GH Actions build agents.
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore ${{ inputs.project-folder }}/${{ inputs.project-file }}

#      - name: Decode Keystore
#        id: decode_keystore
#        uses: timheuer/base64-to-file@v1
#        with:
#          fileDir: '${{ github.workspace }}\${{ inputs.project-folder }}'
#          fileName: 'ourkeystore.jks'
#          encodedString: ${{ secrets.keystore }}

      - name: Version the app
        uses: managedcode/MAUIAppVersion@v1
        with: 
          csproj: ${{ inputs.project-folder }}/${{ inputs.project-file }}
          version: ${{ github.run_number }} # to keep value unique
          displayVersion: ${{ inputs.build-version }}.${{ github.run_number }}
          printFile: true # optional

      - name: Publish MAUI Android AAB
        run: dotnet publish ${{ inputs.project-folder }}/${{inputs.project-file}} -c ${{ inputs.build-config }} -f ${{ inputs.dotnet-version-target }}-android /p:AndroidPackageFormats=apk --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.scn.BrickController2-dev
          path: ${{inputs.project-folder}}/bin/${{ inputs.build-config }}/${{ inputs.dotnet-version-target }}-android/*Signed.a*
        
#      - uses: r0adkll/upload-google-play@v1.0.17
#        name: Upload Android Artifact to Play Console
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.playstore-service-account }}
#          packageName: ${{ inputs.package-name }}
#          releaseFiles: ${{ github.workspace }}\${{ inputs.project-folder }}\bin\${{ inputs.build-config }}\${{ inputs.dotnet-version-target }}-android\${{ inputs.package-name }}-Signed.aab
#          track: internal
